import { Injectable } from "@angular/core";


@Injectable()
export class lang{

   private lang = [{
    "intake": {
    "business_partners.page.title": "شرکای تجاری",
    "business_partners.section.add_partner.add_button": "اضافه کردن شریک تجاری جدید",
    "business_partners.section.add_partner.description": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "business_partners.section.add_partner.field.email": "پست الکترونیکی",
    "business_partners.section.add_partner.title": "شرکای تجاریتان را اضافه کنید",
    "business_partners.section.do_you_have.description": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "business_partners.section.do_you_have.no": "خیر، تنها هستم",
    "business_partners.section.do_you_have.title": "آیا شرکای تجاری دارید؟",
    "business_partners.section.do_you_have.yes": "بله، من شرکای تجاری دارم",
    "company_overview.page.title": "در خواستتان را ارسال کنید",
    "company_overview.section.challenges.field.how_overcome": "توضیح دهید چگونه از این مشکل عبور کردید",
    "company_overview.section.challenges.field.why_important": "توضیح دهید چرا این موضوع برای شما مهم است",
    "company_overview.section.challenges.title": "چلنج های اصلی استارتاپ",
    "company_overview.section.company_idea.field.company_start": "چرا استارتاپ را شروع کردید؟",
    "company_overview.section.company_idea.field.describe_product": "محصول یا خدمت شما",
    "company_overview.section.company_idea.title": "ایده استارتاپ",
    "company_overview.section.company_information.description": "توضیحات استارتاپ",
    "company_overview.section.company_information.field.address": "آدرس",
    "company_overview.section.company_information.field.amount_of_employees": "تعداد کارمندان",
    "company_overview.section.company_information.field.amount_of_owners": "تعداد فاندر ها",
    "company_overview.section.company_information.field.awareness": "طریقه آشنایی",
    "company_overview.section.company_information.field.city": "شهر",
    "company_overview.section.company_information.field.company_branch": "شاخه",
    "company_overview.section.company_information.field.company_name": "نام استارتاپ",
    "company_overview.section.company_information.field.country": "کشور",
    "company_overview.section.company_information.field.curren_active_incubator": "متن ساختگی با تولید سادگی نامفهوم",
    "company_overview.section.company_information.field.email": "پست الکترونیکی",
    "company_overview.section.company_information.field.name_of_incubator_program": "متن ساختگی با تولید سادگی نامفهوم2",
    "company_overview.section.company_information.field.phone": "تلفن",
    "company_overview.section.company_information.field.start_date": "تاریخ شروع",
    "company_overview.section.company_information.field.website": "وب سایت",
    "company_overview.section.company_information.field.zipcode": "کد پستی",
    "company_overview.section.company_information.title": "اطلاعات استارتاپ",
    "company_overview.section.curren_earning.field.cost_amount": "هزینه ماهیانه فعلی",
    "company_overview.section.curren_earning.field.earning_amount": "درآمد ماهیانه فعلی",
    "company_overview.section.curren_earning.field.investment_amount": "سرمایه فعلی",
    "company_overview.section.team_members.education": "تحصیلات",
    "company_overview.section.team_members.field.birthday": "تاریخ تولد",
    "company_overview.section.team_members.field.company": "نام شرکت",
    "company_overview.section.team_members.field.diploma_achieved": "مدرک دریافت شده",
    "company_overview.section.team_members.field.education": "مقطع",
    "company_overview.section.team_members.field.email": "پست الکترونیک",
    "company_overview.section.team_members.field.entrepreneur": "نوع پروفایل شما",
    "company_overview.section.team_members.field.firstname": "نام",
    "company_overview.section.team_members.field.from": "تاریخ شروع",
    "company_overview.section.team_members.field.motivation": "چرا در استارتاپ مشارکت می کنید و انگیزه شما چیست؟",
    "company_overview.section.team_members.field.participation": "نحوه مشارکت",
    "company_overview.section.team_members.field.phone": "تلفن",
    "company_overview.section.team_members.field.role": "نقش",
    "company_overview.section.team_members.field.social_security_number": "کد ملی",
    "company_overview.section.team_members.field.surname": "نام خانوادگی",
    "company_overview.section.team_members.field.target": "چه چیزی میخواهید بدست بیاورید، هدف شما چیست؟",
    "company_overview.section.team_members.field.to": "تاریخ پایان",
    "company_overview.section.team_members.relevant_work_experiences": "تجربه کاری مرتبط",
    "company_overview.section.team_members.title": "اعضای تیم",
    "completed.page.title": "اتمام",
    "completed.section.done.description": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "completed.section.done.title": "مراحل به پایان رسید",
    "entrepreneur_profile_result.page.title": "نتیجه پروفایل کارآفرینی",
    "entrepreneur_profile_result.section.choice_type.description": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "entrepreneur_profile_result.section.choice_type.field.type": "نوع پروفایل شما",
    "entrepreneur_profile_result.section.choice_type.title": "چه نوع شخصیت کارآفرینی دارید؟",
    "entrepreneur_profile_result.section.type.description": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "entrepreneur_profile_result.section.type.title": "نوع پروفایل کارآفرینی",
    "entrepreneur_profile_test.page.section.questions.description": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "entrepreneur_profile_test.page.section.questions.title": "چه نوع شخصیت کارآفرینی دارید؟",
    "entrepreneur_profile_test.page.title": "آزمون پروفایل کارآفرینی",
    "focus_points.page.title": "نقاط تمرکز",
    "focus_points.section.important_subject.description": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "focus_points.section.important_subject.title": "کدام یک از موارد زیر برای شما مهم تر است؟",
    "general_information.page.title": "اطلاعات استارتاپ",
    "general_information.section.company_idea.description": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "general_information.section.company_idea.field.company_start": "چرا استارتاپ را شروع کردید",
    "general_information.section.company_idea.field.describe_product": "محصول خود را شرح دهید",
    "general_information.section.company_idea.title": "ایده استارتاپ",
    "general_information.section.company_information.description": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "general_information.section.company_information.does_your_company_participate_in_any_incubator_program": "متن ساختگی با تولید سادگی نامفهوم",
    "general_information.section.company_information.does_your_company_participate_in_any_incubator_program.tooltip": "متن ساختگی با تولید سادگی نامفهوم",
    "general_information.section.company_information.field.address": "آدرس",
    "general_information.section.company_information.field.amount_of_employees": "تعداد کارمندان",
    "general_information.section.company_information.field.amount_of_owners": "تعداد فاندر ها",
    "general_information.section.company_information.field.city": "شهر",
    "general_information.section.company_information.field.company_branch": "شاخه",
    "general_information.section.company_information.field.company_name": "نام استارتاپ به لاتین",
    "general_information.section.company_information.field.country": "کشور",
    "general_information.section.company_information.field.curren_active_incubator": "متن ساختگی با تولید سادگی نامفهوم",
    "general_information.section.company_information.field.date": "تاریخ",
    "general_information.section.company_information.field.email": "پست الکترونیکی",
    "general_information.section.company_information.field.name_of_incubator_program": "متن ساختگی با تولید سادگی نامفهوم۲",
    "general_information.section.company_information.field.phone": "تلفن",
    "general_information.section.company_information.field.website": "وب سایت",
    "general_information.section.company_information.field.zipcode": "کد پستی",
    "general_information.section.company_information.heading.address_information": "اطلاعات مسکونی",
    "general_information.section.company_information.heading.company_information": "اطلاعات استارتاپ",
    "general_information.section.company_information.heading.contact_information": "اطلاعات تماس",
    "general_information.section.company_information.how_many_employees_does_the_company_have": "تعداد کارمندان شرکت",
    "general_information.section.company_information.how_many_employees_does_the_company_have.tootltip": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "general_information.section.company_information.how_many_owners_does_the_company_have": "چند نفر در استارتاپ فاندر هستند؟",
    "general_information.section.company_information.how_many_owners_does_the_company_have.tooltip": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "general_information.section.company_information.title": "اطلاعات استارتاپ",
    "general_information.section.company_information.when_did_you_start_the_company": "چه زمانی استارتاپ شروع به کار کرد",
    "general_information.section.company_information.when_did_you_start_the_company.tooltip": "چه زمانی استارتاپ شروع به کار کرد",
    "general_information.section.curren_earning.current_monthly_costs": "هزینه ماهیانه فعلی",
    "general_information.section.curren_earning.current_monthly_costs.tooltip": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "general_information.section.curren_earning.current_monthly_earnings": "درآمد ماهیانه فعلی",
    "general_information.section.curren_earning.current_monthly_earnings.tooltip": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "general_information.section.curren_earning.description": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "general_information.section.curren_earning.field.cost_amount": "مقدار",
    "general_information.section.curren_earning.field.earning_amount": "مقدار",
    "general_information.section.curren_earning.field.investment_amount": "مقدار",
    "general_information.section.curren_earning.title": "درآمد و هزینه های فعلی استارتاپ",
    "general_information.section.curren_earning.what_kind_of_investment_have_you_received_so_far": "چقدر سرمایه گذاری جذب کرده اید",
    "general_information.section.curren_earning.what_kind_of_investment_have_you_received_so_far.tooltip": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "introduction.page.title": "معرفی",
    "introduction.section.video_introduction.description": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "introduction.section.video_introduction.title": "ویديو معرفی",
    "main_obstacles.page.title": "موانع اصلی",
    "main_obstacles.section.bigest_obstacles.description": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "main_obstacles.section.bigest_obstacles.field.how_overcome": "توضیح دهید چگونه از این مشکل عبور کردید",
    "main_obstacles.section.bigest_obstacles.field.why_important": "توضیح دهید چرا این موضوع برای شما مهم است",
    "main_obstacles.section.bigest_obstacles.title": "موانع اصلی استارتاپ شما",
    "personal_information.page.title": "اطلاعات شخصی",
    "personal_information.section.education.description": null,
    "personal_information.section.education.field.add_button": "ایجاد مقطع تحصیلی",
    "personal_information.section.education.field.diploma_achieved": "مدرک دریافت کرده اید؟",
    "personal_information.section.education.field.education": "مقطع",
    "personal_information.section.education.title": "تحصیلات",
    "personal_information.section.work.add_button": "ایجاد سابقه کاری",
    "personal_information.section.work.description": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "personal_information.section.work.field.company": "نام شرکت",
    "personal_information.section.work.field.from": "تاریخ شروع",
    "personal_information.section.work.field.role": "توضیح نقش و مسئولیت ها",
    "personal_information.section.work.field.to": "تاریخ پایان",
    "personal_information.section.work.title": "سابقه کاری",
    "personal_information.section.your_personal.description": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "personal_information.section.your_personal.field.awareness": "طریقه آشنایی",
    "personal_information.section.your_personal.field.awareness_other": "سایر",
    "personal_information.section.your_personal.field.birthday": "تاریخ تولد",
    "personal_information.section.your_personal.field.email": "پست الکترونیک",
    "personal_information.section.your_personal.field.firstname": "نام",
    "personal_information.section.your_personal.field.phone": "تلفن",
    "personal_information.section.your_personal.field.social_security_number": "کد ملی",
    "personal_information.section.your_personal.field.surname": "نام خانوادگی",
    "personal_information.section.your_personal.title": "اطلاعات شخصی شما",
    "personal_participation.page.title": "مشارکت شخصی",
    "personal_participation.section.participation.description": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "personal_participation.section.participation.field.full_time": "تمام وقت",
    "personal_participation.section.participation.field.motivation": "چرا در استارتاپ مشارکت می کنید و انگیزه شما چیست؟",
    "personal_participation.section.participation.field.part_time": "پاره وقت",
    "personal_participation.section.participation.field.role": "نقش شما",
    "personal_participation.section.participation.field.target": "چه چیزی میخواهید بدست بیاورید، هدف شما چیست؟",
    "personal_participation.section.participation.title": "مشارکت، نقش و هدف",
    "personal_participation.section.participation.what_is_your_participation": "نحوه مشارکت شما در %company%",
    "personal_participation.section.participation.what_is_your_participation.tooltip": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "personal_participation.section.participation.what_is_your_role": "نقش شما در %company%",
    "personal_participation.section.participation.what_is_your_role.tooltip": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "set_password.page.title": "تغییر کلمه عبور",
    "set_password.section.set_password.field.confirm_password": "تغییر کلمه عبور",
    "set_password.section.set_password.field.password": "کلمه عبور",
    "set_password.section.set_password.submit": "تغییر کلمه عبور",
    "set_password.section.set_password.title": "تغییر کلمه عبور",
    "signup.page.title": "ثبت نام",
    "signup.section.signup.already_have_account": "حساب کاربری دارید؟ وارد شوید",
    "signup.section.signup.description": "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است.",
    "signup.section.signup.field.company_name": "نام استارتاپ به لاتین",
    "signup.section.signup.field.email": "پست الکترونیکی",
    "signup.section.signup.field.firstname": "نام",
    "signup.section.signup.field.surename": "نام خانوادگی",
    "signup.section.signup.submit": "ثبت نام",
    "signup.section.signup.title": "در سکو ثبت نام کنید"
    },
    "business_plan": {
    "business_partners.page.title": "شرکای تجاری",
    "business_partners.section.delete_partner.description": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "business_partners.section.delete_partner.title": "حذف یک شریک تجاری",
    "business_partners.section.partners.add_button": "اضافه کردن یک شریک دیگر",
    "business_partners.section.partners.field.birthday": "تاریخ تولد",
    "business_partners.section.partners.field.email": "پست الکترونیکی",
    "business_partners.section.partners.field.name": "نام و نام خانوادگی",
    "business_partners.section.partners.field.phone": "تلفن",
    "business_partners.section.partners.field.role": "نقش",
    "business_partners.section.partners.field.saku_status": "وضعیت در سکو",
    "business_partners.section.partners.field.saku_status.active": "فعال",
    "business_partners.section.partners.field.saku_status.in_active": "غیر فعال",
    "coach_meeting_1.page.title": "جلسه با مربی",
    "coach_meeting_1.section.plan.description": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "coach_meeting_1.section.plan.items": "آیتم های جلسه",
    "coach_meeting_1.section.plan.title": "یک جلسه با مربی خود برنامه ریزی کنید",
    "coach_meeting_2.page.title": "جلسه با مربی",
    "coach_meeting_2.section.plan.description": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "coach_meeting_2.section.plan.items": "آیتم های جلسه",
    "coach_meeting_2.section.plan.title": "یک جلسه با مربی خود برنامه ریزی کنید",
    "coach_meeting_3.page.title": "جلسه با مربی",
    "coach_meeting_3.section.plan.description": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "coach_meeting_3.section.plan.items": "آیتم های جلسه",
    "coach_meeting_3.section.plan.title": "یک جلسه با مربی خود برنامه ریزی کنید",
    "coach_meeting_4.page.title": "جلسه با مربی",
    "coach_meeting_4.section.plan.description": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "coach_meeting_4.section.plan.items": "آیتم های جلسه",
    "coach_meeting_4.section.plan.title": "یک جلسه با مربی خود برنامه ریزی کنید",
    "company_information.page.title": "اطتلاعات استارتاپ",
    "company_information.section.company_information.field.address": "آدرس",
    "company_information.section.company_information.field.city": "شهر",
    "company_information.section.company_information.field.coc_number": "شماره اقتصادی",
    "company_information.section.company_information.field.coc_registration_date": "تاریخ ثبت",
    "company_information.section.company_information.field.company_branch": "شاخه",
    "company_information.section.company_information.field.company_name": "نام استارتاپ به لاتین",
    "company_information.section.company_information.field.country": "کشور",
    "company_information.section.company_information.field.date": "تاریخ",
    "company_information.section.company_information.field.email": "پست الکترونیکی",
    "company_information.section.company_information.field.legal_form": "نوع",
    "company_information.section.company_information.field.phone": "تلفن",
    "company_information.section.company_information.field.tax_number": "شماره مالیاتی",
    "company_information.section.company_information.field.website": "وب سایت",
    "company_information.section.company_information.field.zipcode": "کد پستی",
    "company_information.section.company_information.heading.address_information": "اطلاعات مسکونی",
    "company_information.section.company_information.heading.company_information": "اطلاعات استارتاپ",
    "company_information.section.company_information.heading.contact_information": "اطلاعات تماس",
    "company_information.section.company_information.heading.legal_information": "اطلاعات حقوقی",
    "company_information.section.ips.description": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "company_information.section.ips.field.obtained": "دارا میباشد؟",
    "company_information.section.ips.field.obtained.not_yet": "نه هنوز",
    "company_information.section.ips.field.obtained.yes": "بله",
    "company_information.section.ips.insurances.add": "ایجاد یک بیمه دیگر",
    "company_information.section.ips.insurances.checkbox": "استارتاپ نیاز به بیمه دارد",
    "company_information.section.ips.insurances.kind": "نوع بیمه",
    "company_information.section.ips.insurances.title": "بیمه ها",
    "company_information.section.ips.permits.add": "ایجاد یک مجوز دیگر",
    "company_information.section.ips.permits.checkbox": "استارتاپ نیاز به مجوز دارد",
    "company_information.section.ips.permits.kind": "نوع مجوز",
    "company_information.section.ips.permits.title": "مجوز ها",
    "company_information.section.ips.subsidies.add": "ایجاد یک یارانه دیگر",
    "company_information.section.ips.subsidies.checkbox": "استارتاپ نیاز به یارانه دارد",
    "company_information.section.ips.subsidies.kind": "نوع یارانه",
    "company_information.section.ips.subsidies.title": "یارانه ها",
    "company_information.section.ips.title": "بیمه، مجوز و یارانه ها",
    "competition.page.title": "رقابت",
    "competition.section.advantage.advantage_competitors": "بزرگترین مزیت شما نسبت به رقبا شما چیست؟",
    "competition.section.advantage.description": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "competition.section.advantage.title": "بزرگترین مزیت شما چیست؟",
    "competition.section.advantage.unique_compare_to_competitor": "چه چیزی باعث می شود شرکت شما در مقایسه با رقبای دیگر منحصر به فرد باشد؟",
    "competition.section.list.add_button": "یک رقیب دیگر اضافه کنید",
    "competition.section.list.description": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "competition.section.list.field.city_country": "شهر و کشور",
    "competition.section.list.field.description": "توضیحات کوتاه",
    "competition.section.list.field.name": "نام",
    "competition.section.list.field.webiste": "وب سایت",
    "competition.section.list.title": "بزرگترین رقبای خود را فهرست کنید",
    "core_value_questions.page.title": "سوالات ارزش اصلی",
    "core_value_questions.section.questions.description": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "core_value_questions.section.questions.no": "نه / اعمال نمی شود",
    "core_value_questions.section.questions.title": "ارزش های اصلی که برای شرکت شما مهم هستند را انتخاب کنید",
    "core_value_questions.section.questions.yes": "بله",
    "core_value.page.title": "ارزشهای اصلی",
    "core_value.section.core_values.add_button": "ایجاد ارزش اصلی",
    "core_value.section.core_values.description": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "core_value.section.core_values.field.core_value": "ارزش اصلی",
    "core_value.section.core_values.title": "ارزشهای اصلی",
    "customer_gains.page.title": "دست آورد های مشتری",
    "customer_gains.section.answers.add_button": "ایجاد دست آورد مشتری",
    "customer_gains.section.answers.description": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "customer_gains.section.answers.field.description": "توضیح دهید %job% چگونه مشتری را راضی نگاه میدارد",
    "customer_gains.section.answers.field.description_default": "توضیح دهید چگونه مشتری راضی میشود",
    "customer_gains.section.answers.field.often": "اغلب چگونه اتفاق می‌افتد",
    "customer_gains.section.answers.field.pain": "درجه ارتباط",
    "customer_gains.section.answers.title": "دست آورد های مشتری چیست؟",
    "customer_jobs.page.title": "فعالیت های مشتری",
    "customer_jobs.section.answers.add_button": "ایجاد فعالیت مشتری",
    "customer_jobs.section.answers.description": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "customer_jobs.section.answers.field.description": "توضیح دهید %job% چگونه انجام میشود",
    "customer_jobs.section.answers.field.description_default": "توضیح دهید چگونه انجام میشود",
    "customer_jobs.section.answers.field.importance": "درجه اهمیت",
    "customer_jobs.section.answers.field.often": "اغلب چگونه اتفاق می‌افتد",
    "customer_jobs.section.answers.title": "فعالیت های خاص مشتری چیست؟",
    "customer_pains.page.title": "سختی های مشتری",
    "customer_pains.section.answers.add_button": "ایجاد سختی مشتری",
    "customer_pains.section.answers.description": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "customer_pains.section.answers.field.description": "توضیح دهید %job% چگونه هزینه بر است",
    "customer_pains.section.answers.field.description_default": "توضیح دهید چگونه هزینه میشود",
    "customer_pains.section.answers.field.often": "اغلب چگونه اتفاق می‌افتد",
    "customer_pains.section.answers.field.pain": "درجه سختی",
    "customer_pains.section.answers.title": "سختی های مشتری چیست؟",
    "gains_questions.page.title": "سوالات دست آورد های مشتری",
    "gains_questions.section.questions.description": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "gains_questions.section.questions.title": "چه چیز هایی دست آورد مشتری شما است؟",
    "jobs_questions.page.title": "سوالات فعالیت های مشتری",
    "jobs_questions.section.questions.description": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "jobs_questions.section.questions.title": "چه چیز هایی توسط مشتری شما کامل میشود؟",
    "market_development.page.title": "توسعه بازار",
    "market_development.section.market.description": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "market_development.section.market.field.company_market": "در چه بازاری استارتاپ شما فعالیت میکند",
    "market_development.section.market.field.international_market": "توسعه بازار جهانی",
    "market_development.section.market.field.local_market": "توسعه بازار داخلی",
    "market_development.section.market.title": "بازار شما چگونه است؟",
    "market_development.section.resource.add_button": "یک منبع دیگر اضافه کنید",
    "market_development.section.resource.description": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "market_development.section.resource.field.author": "نویسنده",
    "market_development.section.resource.field.publisher": "ناشر",
    "market_development.section.resource.field.title": "عنوان",
    "market_development.section.resource.field.type": "نوع منبع",
    "market_development.section.resource.field.url": "وب سایت",
    "market_development.section.resource.title": "منابع",
    "market_potential.page.title": "پتانسیل بازار",
    "market_potential.section.how.description": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "market_potential.section.how.field.market_development_predictions": "بازار هدف شما چقدر بزرگ است و چگونه این بر اساس پیش بینی های توسعه بازار شما توسعه می یابد؟",
    "market_potential.section.how.field.target_market_in_current_market": "بازار هدف شما چقدر ارزش دارد؟",
    "market_potential.section.how.title": "گروه هدف شما چقدر بزرگ است",
    "market_potential.section.resource.add_button": "یک منبع دیگر اضافه کنید",
    "market_potential.section.resource.description": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "market_potential.section.resource.field.author": "نویسنده",
    "market_potential.section.resource.field.publisher": "ناشر",
    "market_potential.section.resource.field.title": "عنوان",
    "market_potential.section.resource.field.type": "نوع منبع",
    "market_potential.section.resource.field.url": "وب سایت",
    "market_potential.section.resource.title": "منابع",
    "marketing_mix_people.page.title": "مجموعه بازاریابی: مردم",
    "marketing_mix_people.section.your_product.description": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "marketing_mix_people.section.your_product.field.describe_your_people": "مردم خود را توصیف کنید",
    "marketing_mix_people.section.your_product.questions": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "marketing_mix_people.section.your_product.qustion": "سوالاتی که به شما کمک می کند:",
    "marketing_mix_people.section.your_product.title": "مردم شما",
    "marketing_mix_place_and_distribution.page.title": "مجموعه بازاریابی: محل و توزیع",
    "marketing_mix_place_and_distribution.section.your_product.description": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "marketing_mix_place_and_distribution.section.your_product.field.describe_your_distribution": "محل و توزیع خود را شرح دهید",
    "marketing_mix_place_and_distribution.section.your_product.questions": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "marketing_mix_place_and_distribution.section.your_product.qustion": "سوالاتی که به شما کمک می کند:",
    "marketing_mix_place_and_distribution.section.your_product.title": "محل و توزیع شما",
    "marketing_mix_price.page.title": "مجموعه بازاریابی: قیمت",
    "marketing_mix_price.section.your_product.description": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "marketing_mix_price.section.your_product.field.describe_your_price": "قیمت خود را شرح دهید",
    "marketing_mix_price.section.your_product.questions": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "marketing_mix_price.section.your_product.qustion": "سوالاتی که به شما کمک می کند:",
    "marketing_mix_price.section.your_product.title": "قیمت شما",
    "marketing_mix_process.page.title": "مجموعه بازاریابی: فرایند",
    "marketing_mix_process.section.your_product.description": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "marketing_mix_process.section.your_product.field.describe_your_people": "فرآیند خود را شرح دهید",
    "marketing_mix_process.section.your_product.questions": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "marketing_mix_process.section.your_product.qustion": "سوالاتی که به شما کمک می کند:",
    "marketing_mix_process.section.your_product.title": "فرآیند شما",
    "marketing_mix_product.page.title": "مجموعه بازاریابی: محصول",
    "marketing_mix_product.section.your_product.description": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "marketing_mix_product.section.your_product.field.describe_your_product": "محصول یا خدمات خود را شرح دهید",
    "marketing_mix_product.section.your_product.questions": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "marketing_mix_product.section.your_product.qustion": "سوالاتی که به شما کمک می کند:",
    "marketing_mix_product.section.your_product.title": "محصول یا خدمات شما",
    "marketing_mix_promotion.page.title": "ترکیب بازاریابی: ارتقاء",
    "marketing_mix_promotion.section.your_product.description": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "marketing_mix_promotion.section.your_product.field.describe_your_promotion": "ارتقا خود را شرح دهید",
    "marketing_mix_promotion.section.your_product.questions": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "marketing_mix_promotion.section.your_product.qustion": "سوالاتی که به شما کمک می کند:",
    "marketing_mix_promotion.section.your_product.title": "ارتقاء شما",
    "marketing_mix.audience.description": "برای چند سوال بعدی، از شما می خواهیم که به سوالات مخاطبان مورد نظرتان پاسخ دهید. به همین دلیل %persona% حضور دارد!",
    "marketing_mix.audience.title": "مخاطب هدف شما",
    "mission_inspiration.page.title": "ماموریت",
    "mission_inspiration.section.questions.description": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "mission_inspiration.section.questions.no": "نه / اعمال نمی شود",
    "mission_inspiration.section.questions.title": "موضوعاتی را که برای ماموریت شرکت شما مهم هستند را انتخاب کنید",
    "mission_inspiration.section.questions.yes": "بله",
    "mission.page.title": "ماموریت",
    "mission.section.mission.description": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "mission.section.mission.field.mission": "مأموریت خود را شرح دهید",
    "mission.section.mission.hint": "موضوعاتی که برای مأموریت شما مهم هستند:",
    "mission.section.mission.title": "ماموریت",
    "opportunities_and_threats_descriptions.page.title": "بررسی فرصت و تهدیدات شرکت",
    "opportunities_and_threats_descriptions.section.opportunity.add_button": "یک فرصت اضافه کنید",
    "opportunities_and_threats_descriptions.section.opportunity.description": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "opportunities_and_threats_descriptions.section.opportunity.field.maximize_opportunities": "چگونه ارزش فرصت خود را به حداکثر می رسانید؟",
    "opportunities_and_threats_descriptions.section.opportunity.field.strengths": "توضیح دهید چرا %hint% یکی از فرصت های استارتاپ است",
    "opportunities_and_threats_descriptions.section.opportunity.title": "فرصت های خود را لیست کنید",
    "opportunities_and_threats_descriptions.section.threat.add_button": "یک تهدید دیگر اضافه کنید",
    "opportunities_and_threats_descriptions.section.threat.description": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "opportunities_and_threats_descriptions.section.threat.field.deal_threats": "چگونه می توان به بهترین نحو با تهدی ها مقابله کرد؟",
    "opportunities_and_threats_descriptions.section.threat.field.weakness": "توضیح دهید چرا %hint% یکی از تهدید های استارتاپ است",
    "opportunities_and_threats_descriptions.section.threat.title": "تهدید های خود را فهرست کنید",
    "opportunities_and_threats_questions.page.title": " فرصت و تهدیدات شرکت",
    "opportunities_and_threats_questions.section.questions.description": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "opportunities_and_threats_questions.section.questions.hint": "آیا %hint% یک فرصت یا تهدید است که می تواند در آینده اتفاق بیفتد یا نقش مهمی ندارد.",
    "opportunities_and_threats_questions.section.questions.no": "نقش مهمی ایفا نمی کند",
    "opportunities_and_threats_questions.section.questions.opportunity": "فرصت",
    "opportunities_and_threats_questions.section.questions.threat": "تهدید",
    "opportunities_and_threats_questions.section.questions.title": "موارد زیر را تقسیم کنید",
    "pains_questions.page.title": "سوالات سختی های مشتری",
    "pains_questions.section.questions.description": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "pains_questions.section.questions.title": "چه چیز هایی باعث سختی مشتری شما میشود؟",
    "persona_solutions.page.title": "راه حل های شخصیت تعریف شده",
    "persona_solutions.section.solution.description": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "persona_solutions.section.solution.problem": "چگونه %persona% در حال حاضر مشکلش را حل می کند؟",
    "persona_solutions.section.solution.solution": "چگونه محصول شما کمک میکند آن مشکل حل شود؟",
    "persona_solutions.section.solution.title": "راه حل ها",
    "persona_solutions.section.your_persona.biggest_gain": "مهم ترین دست آورد ها",
    "persona_solutions.section.your_persona.biggest_pain": "مهم ترین سختی ها",
    "persona_solutions.section.your_persona.description": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "persona_solutions.section.your_persona.title": "شخصیت تعریف شده شما",
    "persona.page.title": "شخصیت",
    "persona.section.define.add_hobby": "ایجاد یک عادت",
    "persona.section.define.description": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "persona.section.define.field.age": "سن",
    "persona.section.define.field.careless": "بی توجه",
    "persona.section.define.field.cautious": "محتاط",
    "persona.section.define.field.city": "شهر",
    "persona.section.define.field.confident": "مطمئن",
    "persona.section.define.field.country": "کشور",
    "persona.section.define.field.curous": "کنجکاو",
    "persona.section.define.field.detached": "منفصل",
    "persona.section.define.field.education_level": "تحصیلات",
    "persona.section.define.field.efficient": "کارآمد",
    "persona.section.define.field.friendly": "دوستانه",
    "persona.section.define.field.gender": "جنسیت",
    "persona.section.define.field.heading.hobby": "علایق و عادت ها",
    "persona.section.define.field.heading.motivation": "انگیزه",
    "persona.section.define.field.heading.personality": "هویت",
    "persona.section.define.field.hobby": "عادت/علاقه",
    "persona.section.define.field.income_level": "درآمپ",
    "persona.section.define.field.motivation": "چه چیزی شخصیت تعریف شده شمارا وادار میکند خرید کند یا از خدمتی استفاده کند؟",
    "persona.section.define.field.name": "نام",
    "persona.section.define.field.nervous": "عصبی",
    "persona.section.define.field.occupation": "شغل",
    "persona.section.define.field.outgoin": "برونگرا",
    "persona.section.define.field.reserved": "درونگرا",
    "persona.section.define.field.status": "وضعیت",
    "persona.section.define.title": "یک شخصیت تعریف کنید",
    "strength_and_weakness_descriptions.page.title": "بررسی نقاط قوت و ضعف شرکت",
    "strength_and_weakness_descriptions.section.strengths.add_button": "یک نقطه قوت اضافه کنید",
    "strength_and_weakness_descriptions.section.strengths.description": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "strength_and_weakness_descriptions.section.strengths.field.maximize_strengths": "چگونه ارزش نقاط قوت خود را به حداکثر می رسانید؟",
    "strength_and_weakness_descriptions.section.strengths.field.strengths": "توضیح دهید چرا %hint% یکی از نقاط قوت استارتاپ است",
    "strength_and_weakness_descriptions.section.strengths.title": "نقاط قوت خود را لیست کنید",
    "strength_and_weakness_descriptions.section.weaknesses.add_button": "یک ضعف دیگر اضافه کنید",
    "strength_and_weakness_descriptions.section.weaknesses.description": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "strength_and_weakness_descriptions.section.weaknesses.field.deal_weakness": "چگونه می توان به بهترین نحو با ضعف ها مقابله کرد؟",
    "strength_and_weakness_descriptions.section.weaknesses.field.weakness": "توضیح دهید چرا %hint% یکی از ضعف های استارتاپ است",
    "strength_and_weakness_descriptions.section.weaknesses.title": "ضعف های خود را فهرست کنید",
    "strength_and_weakness_questions.page.title": "نقاط قوت و ضعف شرکت",
    "strength_and_weakness_questions.section.questions.description": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "strength_and_weakness_questions.section.questions.hint": "آیا %hint% یک قدرت یا ضعف شرکتی است که شما در حال حاضر آن را تشکیل می دهید یا نقش مهمی ندارد.",
    "strength_and_weakness_questions.section.questions.no": "نقش مهمی ایفا نمی کند",
    "strength_and_weakness_questions.section.questions.strength": "نقطه قوت",
    "strength_and_weakness_questions.section.questions.title": "موارد زیر را تقسیم کنید",
    "strength_and_weakness_questions.section.questions.weakness": "ضعف",
    "target_group.page.title": "گروه هدف",
    "target_group.section.who.description": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "target_group.section.who.target_group": "گروه هدف",
    "target_group.section.who.title": "چه کسانی گروه هدف شما هستند؟",
    "the_idea.page.title": "ایده",
    "the_idea.section.reason.description": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "the_idea.section.reason.field.achieve": "چه چیزی را میخواهید به دست بیاورید؟",
    "the_idea.section.reason.field.idea": "توضیح مختصر در برای ایده‌تان",
    "the_idea.section.reason.title": "دلیلی که باعث شروع این استارتاپ شد",
    "vision.page.title": "چشم انداز",
    "vision.section.vision.description": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "vision.section.vision.field.mission": "دیدگاه خود را توضیح دهید",
    "vision.section.vision.hint": "موضوعات مورد نظر برای دیدگاه شما مهم است:",
    "vision.section.vision.title": "چشم انداز",
    "welcome.page.title": "به سکو خوش آمدید",
    "welcome.section.congratulations.description": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "welcome.section.congratulations.title": "تبریک! به سکو خوش آمدید",
    "welcome.section.couch.description": "متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است",
    "welcome.section.couch.title": "با مربیتان آشنا شوید"
    },
    "global": {
    "buttons.cancel": "لغو",
    "buttons.delete": "حذف",
    "buttons.next": "قدم بعدی",
    "buttons.previous": "قدم قبلی",
    "buttons.save": "ذخیر اطلاعات"
    },
    "knppaginatorbundle": {
    "label_next": null,
    "label_previous": null
    },
    "user_menu": {
    "logout": "خروج",
    "my_profile": "پروفایل من"
    }
    }];


    getLang(key : string , subey:string){
        return this.lang[0][key][subey];
    }

}